package env

import (
	"strings"
	"testing"
)

var exportEntries = []Entry{
	{Key: "APP_NAME", Value: "envcrypt"},
	{Key: "DB_URL", Value: "postgres://localhost/db"},
	{Key: "SECRET", Value: "it's a secret"},
}

func TestExportDotEnv(t *testing.T) {
	var buf strings.Builder
	err := Export(&buf, exportEntries, ExportOptions{Format: FormatDotEnv})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "APP_NAME=envcrypt") {
		t.Errorf("expected APP_NAME line, got:\n%s", out)
	}
	if !strings.Contains(out, "SECRET=it's a secret") {
		t.Errorf("expected SECRET line, got:\n%s", out)
	}
}

func TestExportShell(t *testing.T) {
	var buf strings.Builder
	err := Export(&buf, exportEntries, ExportOptions{Format: FormatShell})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "export APP_NAME='envcrypt'") {
		t.Errorf("expected shell export for APP_NAME, got:\n%s", out)
	}
	// single quotes inside values must be escaped
	if !strings.Contains(out, "export SECRET='it'\\''s a secret'") {
		t.Errorf("expected escaped single quote in SECRET, got:\n%s", out)
	}
}

func TestExportJSON(t *testing.T) {
	var buf strings.Builder
	err := Export(&buf, exportEntries, ExportOptions{Format: FormatJSON})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	out := buf.String()
	if !strings.HasPrefix(out, "{") || !strings.HasSuffix(strings.TrimSpace(out), "}") {
		t.Errorf("expected JSON object, got:\n%s", out)
	}
	if !strings.Contains(out, `"APP_NAME"`) {
		t.Errorf("expected APP_NAME key in JSON, got:\n%s", out)
	}
}

func TestExportWithComment(t *testing.T) {
	var buf strings.Builder
	err := Export(&buf, exportEntries, ExportOptions{
		Format:  FormatDotEnv,
		Comment: "generated by envcrypt",
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	out := buf.String()
	if !strings.HasPrefix(out, "# generated by envcrypt") {
		t.Errorf("expected comment header, got:\n%s", out)
	}
}

func TestExportJSONCommentSkipped(t *testing.T) {
	var buf strings.Builder
	_ = Export(&buf, exportEntries, ExportOptions{
		Format:  FormatJSON,
		Comment: "should be skipped",
	})
	out := buf.String()
	if strings.Contains(out, "#") {
		t.Errorf("JSON export should not contain comment lines, got:\n%s", out)
	}
}

func TestExportUnknownFormat(t *testing.T) {
	var buf strings.Builder
	err := Export(&buf, exportEntries, ExportOptions{Format: ExportFormat(99)})
	if err == nil {
		t.Fatal("expected error for unknown format, got nil")
	}
}
